name: Java Tests

on:
  push:
    branches: [main, ci/add-github-actions]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Create lib directory
        run: mkdir -p lib

      - name: Download JUnit
        run: |
          wget https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar -O lib/junit.jar
          wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar -O lib/hamcrest-core.jar

      - name: Compile
        run: |
          javac -cp "lib/*" src/**/*.java -d bin/

      - name: Run tests
        run: |
          java -cp "bin:lib/*" org.junit.runner.JUnitCore $(find bin -name "*Test.class" | sed 's/bin\///g' | sed 's/\.class//g' | tr '/' '.')
